// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary design header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef _VCONVCOMBTEST_H_
#define _VCONVCOMBTEST_H_  // guard

#include "verilated_heavy.h"

//==========

class VConvCombTest__Syms;
class VConvCombTest_VerilatedVcd;


//----------

VL_MODULE(VConvCombTest) {
  public:
    
    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(clk,0,0);
    VL_IN8(reset,0,0);
    VL_IN8(tail_bits_valid,0,0);
    VL_IN8(tail_bits_payload,6,0);
    VL_IN8(raw_data_valid,0,0);
    VL_IN8(raw_data_payload_last,0,0);
    VL_IN8(raw_data_payload_fragment,0,0);
    VL_OUT8(decoded_data_valid,0,0);
    VL_OUT8(decoded_data_payload_last,0,0);
    VL_OUT8(decoded_data_payload_fragment,0,0);
    
    // LOCAL SIGNALS
    // Internals; generally not touched by application code
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ ConvCombTest__DOT__encoded_fifo_io_pop_valid;
        CData/*0:0*/ ConvCombTest__DOT__decoder_raw_data_ready;
        CData/*7:0*/ ConvCombTest__DOT__encoder__DOT___zz_r_enc_0;
        CData/*0:0*/ ConvCombTest__DOT__encoder__DOT__raw_data_payload;
        CData/*0:0*/ ConvCombTest__DOT__encoder__DOT__raw_data_valid_1;
        CData/*0:0*/ ConvCombTest__DOT__encoder__DOT__raw_data_last;
        CData/*2:0*/ ConvCombTest__DOT__encoder__DOT__coded_data;
        CData/*0:0*/ ConvCombTest__DOT__encoder__DOT__coded_data_valid_1;
        CData/*6:0*/ ConvCombTest__DOT__encoder__DOT__r_enc_buf;
        CData/*0:0*/ ConvCombTest__DOT__encoder__DOT__raw_data_last_regNext;
        CData/*3:0*/ ConvCombTest__DOT__encoded_fifo__DOT___zz_logic_ram_port0;
        CData/*0:0*/ ConvCombTest__DOT__encoded_fifo__DOT___zz_1;
        CData/*0:0*/ ConvCombTest__DOT__encoded_fifo__DOT__logic_pushPtr_willIncrement;
        CData/*0:0*/ ConvCombTest__DOT__encoded_fifo__DOT__logic_popPtr_willIncrement;
        CData/*0:0*/ ConvCombTest__DOT__encoded_fifo__DOT__logic_ptrMatch;
        CData/*0:0*/ ConvCombTest__DOT__encoded_fifo__DOT__logic_risingOccupancy;
        CData/*0:0*/ ConvCombTest__DOT__encoded_fifo__DOT__logic_pushing;
        CData/*0:0*/ ConvCombTest__DOT__encoded_fifo__DOT__logic_popping;
        CData/*0:0*/ ConvCombTest__DOT__encoded_fifo__DOT__logic_full;
        CData/*0:0*/ ConvCombTest__DOT__encoded_fifo__DOT___zz_io_pop_valid;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__raw_data_fire;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_1;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_2;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_3;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_4;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_5;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_6;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_7;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_8;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_9;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_10;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_11;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_12;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_13;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_14;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_15;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_16;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_18;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_19;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_20;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_21;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_22;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_23;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_24;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_25;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_26;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_27;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_28;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_29;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_30;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_31;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_32;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_33;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_34;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_35;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_36;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_37;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_38;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_39;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_40;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_41;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_42;
    };
    struct {
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_43;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_44;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_45;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_46;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_47;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_48;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_49;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_50;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_51;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_52;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_53;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_54;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_55;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_56;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_57;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_58;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_59;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_60;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_61;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_62;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__node_weight_63;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_0;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_1;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_2;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_3;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_4;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_5;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_6;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_7;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_8;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_9;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_10;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_11;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_12;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_13;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_14;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_15;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_16;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_17;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_18;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_19;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_20;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_21;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_22;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_23;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_24;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_25;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_26;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_27;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_28;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_29;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_30;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_31;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_32;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_33;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_34;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_35;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_36;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_37;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_38;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_39;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_40;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_41;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_42;
    };
    struct {
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_43;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_44;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_45;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_46;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_47;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_48;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_49;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_50;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_51;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_52;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_53;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_54;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_55;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_56;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_57;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_58;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_59;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_60;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_61;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_62;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_63;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_64;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_65;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_66;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_67;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_68;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_69;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_70;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_71;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_72;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_73;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_74;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_75;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_76;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_77;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_78;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_79;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_80;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_81;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_82;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_83;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_84;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_85;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_86;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_87;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_88;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_89;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_90;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_91;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_92;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_93;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_94;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_95;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_96;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_97;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_98;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_99;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_100;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_101;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_102;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_103;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_104;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_105;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_106;
    };
    struct {
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_107;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_108;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_109;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_110;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_111;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_112;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_113;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_114;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_115;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_116;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_117;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_118;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_119;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_120;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_121;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_122;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_123;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_124;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_125;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_126;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__candidate_branches_127;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__raw_data_next;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__raw_data_last_next;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__survival_path_valid;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__survival_path_last;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__raw_data_ready_1;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_64__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_64__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_64__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_65__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_65__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_65__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_66__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_66__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_66__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_67__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_67__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_67__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_68__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_68__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_68__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_69__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_69__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_69__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_70__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_70__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_70__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_71__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_71__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_71__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_72__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_72__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_72__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_73__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_73__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_73__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_74__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_74__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_74__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_75__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_75__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_75__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_76__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_76__DOT__branch_weight_1;
    };
    struct {
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_76__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_77__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_77__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_77__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_78__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_78__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_78__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_79__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_79__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_79__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_80__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_80__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_80__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_81__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_81__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_81__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_82__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_82__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_82__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_83__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_83__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_83__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_84__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_84__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_84__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_85__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_85__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_85__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_86__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_86__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_86__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_87__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_87__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_87__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_88__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_88__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_88__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_89__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_89__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_89__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_90__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_90__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_90__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_91__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_91__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_91__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_92__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_92__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_92__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_93__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_93__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_93__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_94__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_94__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_94__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_95__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_95__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_95__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_96__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_96__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_96__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_97__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_97__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_97__DOT__when_AddCompareSelect_l17;
    };
    struct {
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_98__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_98__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_98__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_99__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_99__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_99__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_100__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_100__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_100__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_101__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_101__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_101__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_102__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_102__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_102__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_103__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_103__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_103__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_104__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_104__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_104__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_105__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_105__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_105__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_106__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_106__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_106__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_107__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_107__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_107__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_108__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_108__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_108__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_109__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_109__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_109__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_110__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_110__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_110__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_111__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_111__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_111__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_112__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_112__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_112__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_113__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_113__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_113__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_114__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_114__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_114__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_115__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_115__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_115__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_116__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_116__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_116__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_117__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_117__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_117__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_118__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_118__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_118__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_119__DOT__branch_weight_0;
    };
    struct {
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_119__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_119__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_120__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_120__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_120__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_121__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_121__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_121__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_122__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_122__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_122__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_123__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_123__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_123__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_124__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_124__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_124__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_125__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_125__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_125__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_126__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_126__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_126__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_127__DOT__branch_weight_0;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_127__DOT__branch_weight_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__addCompareSelect_127__DOT__when_AddCompareSelect_l17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_1;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_2;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_3;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_4;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_5;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_6;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_7;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_8;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_9;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_10;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_11;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_12;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_13;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_14;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_15;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_16;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_17;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_18;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_19;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_20;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_21;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_22;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_23;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_24;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_25;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_26;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_27;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_28;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_29;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_30;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_31;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_1;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_2;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_3;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_4;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_5;
    };
    struct {
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_6;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_7;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_8;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_9;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_10;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_11;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_12;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_13;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_14;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_15;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_16;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_17;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_18;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_19;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_20;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_21;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_22;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_23;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_24;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_25;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_26;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_27;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_28;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_29;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_30;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_31;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_32;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_33;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_34;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_35;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_36;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_37;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_38;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_39;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_40;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_41;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_42;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_43;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_44;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_45;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_46;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_47;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_32;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_33;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_34;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_35;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_36;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_37;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_38;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_39;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_40;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_41;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_42;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_43;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_44;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_45;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_46;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_47;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_48;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_49;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_50;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_51;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_52;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_53;
    };
    struct {
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_54;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_55;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_48;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_49;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_50;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_51;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_52;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_53;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_54;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_55;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_56;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_57;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_58;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_59;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_56;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_57;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_58;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_59;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_60;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_61;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_60;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_61;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_val_62;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__minVal_1__DOT___zz_min_idx_62;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT___zz_ram_select;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT___zz_decoded_ram_select;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT___zz_decoded_ram_select_1;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT___zz_decoded_ram_select_2;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT___zz_ram_addr_read_2;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__ram_select;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__ram_addr_write;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__pkg_tail;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__tb_finish;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__when_Traceback_l48;
        CData/*1:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__decoded_ram_select;
        CData/*7:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__ram_addr_read;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__pipe_halt;
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__min_cursor;
        CData/*6:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__cursor;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__tb_node_data;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__tb_node_valid_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__tb_node_last;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__tail_repeat;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__goto_tail;
        CData/*2:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__halt_cnt;
        CData/*2:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__traceback_state;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__when_Traceback_l104;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__when_Traceback_l153;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo_io_pop_valid;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__fifo_pop_ready;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__decoded_data_valid_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__data_last;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__decoded_data_last;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__decoded_data;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__reorder_state;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__when_ReorderLifo_l54;
        CData/*2:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT___zz_logic_ram_port0;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT___zz_1;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT__logic_pushPtr_willIncrement;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT__logic_popPtr_willIncrement;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT__logic_ptrMatch;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT__logic_risingOccupancy;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT__logic_pushing;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT__logic_popping;
    };
    struct {
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT__logic_full;
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT___zz_io_pop_valid;
        SData/*9:0*/ ConvCombTest__DOT__encoded_fifo__DOT__logic_pushPtr_valueNext;
        SData/*9:0*/ ConvCombTest__DOT__encoded_fifo__DOT__logic_pushPtr_value;
        SData/*9:0*/ ConvCombTest__DOT__encoded_fifo__DOT__logic_popPtr_valueNext;
        SData/*9:0*/ ConvCombTest__DOT__encoded_fifo__DOT__logic_popPtr_value;
        SData/*8:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__lifo_head_cursor;
        SData/*8:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT__logic_pushPtr_valueNext;
        SData/*8:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT__logic_pushPtr_value;
        SData/*8:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT__logic_popPtr_valueNext;
        SData/*8:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT__logic_popPtr_value;
        WData/*87:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__traceback_state_string[3];
        WData/*511:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__decoded_lifo[16];
        WData/*511:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__decoded_last_lifo[16];
        QData/*63:0*/ ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__survival_path;
        QData/*63:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT___zz_survival_path_ram_0_port1;
        QData/*63:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT___zz_survival_path_ram_1_port1;
        QData/*63:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT___zz_survival_path_ram_1_port2;
        CData/*3:0*/ ConvCombTest__DOT__encoded_fifo__DOT__logic_ram[1024];
        CData/*5:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__states_shift_rom[128];
        CData/*0:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__in_data_rom[128];
        QData/*63:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__survival_path_ram_0[168];
        QData/*63:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__survival_path_ram_1[168];
        CData/*2:0*/ ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT__logic_ram[512];
    };
    
    // LOCAL VARIABLES
    // Internals; generally not touched by application code
    CData/*2:0*/ __Vtableidx2;
    CData/*3:0*/ __Vdlyvval__ConvCombTest__DOT__encoded_fifo__DOT__logic_ram__v0;
    CData/*0:0*/ __Vdlyvset__ConvCombTest__DOT__encoded_fifo__DOT__logic_ram__v0;
    CData/*7:0*/ __Vdlyvdim0__ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__survival_path_ram_0__v0;
    CData/*0:0*/ __Vdlyvset__ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__survival_path_ram_0__v0;
    CData/*7:0*/ __Vdlyvdim0__ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__survival_path_ram_1__v0;
    CData/*0:0*/ __Vdlyvset__ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__survival_path_ram_1__v0;
    CData/*1:0*/ __Vdly__ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__decoded_ram_select;
    CData/*2:0*/ __Vdly__ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__halt_cnt;
    CData/*2:0*/ __Vdlyvval__ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT__logic_ram__v0;
    CData/*0:0*/ __Vdlyvset__ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT__logic_ram__v0;
    CData/*7:0*/ __Vdly__ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__ram_addr_read;
    CData/*0:0*/ __Vdly__ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__tail_repeat;
    CData/*2:0*/ __Vdly__ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__traceback_state;
    CData/*0:0*/ __Vdly__ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__reorder_state;
    CData/*0:0*/ __Vclklast__TOP__clk;
    CData/*0:0*/ __Vclklast__TOP__reset;
    SData/*9:0*/ __Vdlyvdim0__ConvCombTest__DOT__encoded_fifo__DOT__logic_ram__v0;
    SData/*8:0*/ __Vdlyvdim0__ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__inverted_order_fifo__DOT__logic_ram__v0;
    SData/*8:0*/ __Vdly__ConvCombTest__DOT__decoder__DOT__lifo_core__DOT__lifo_head_cursor;
    IData/*31:0*/ __Vm_traceActivity;
    QData/*63:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT____Vxrand5;
    QData/*63:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT____Vxrand4;
    QData/*63:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT____Vxrand2;
    QData/*63:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT____Vlvbound1;
    QData/*63:0*/ ConvCombTest__DOT__decoder__DOT__tbu_core__DOT____Vlvbound3;
    QData/*63:0*/ __Vdlyvval__ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__survival_path_ram_0__v0;
    QData/*63:0*/ __Vdlyvval__ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__survival_path_ram_1__v0;
    CData/*4:0*/ __Vtablechg1[128];
    static CData/*0:0*/ __Vtable1_ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__raw_data_next[128];
    static CData/*0:0*/ __Vtable1_ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__raw_data_last_next[128];
    static CData/*0:0*/ __Vtable1_ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__survival_path_valid[128];
    static CData/*0:0*/ __Vtable1_ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__survival_path_last[128];
    static CData/*0:0*/ __Vtable1_ConvCombTest__DOT__decoder__DOT__pmu_core__DOT__raw_data_ready_1[128];
    static WData/*87:0*/ __Vtable2_ConvCombTest__DOT__decoder__DOT__tbu_core__DOT__traceback_state_string[8][3];
    
    // INTERNAL VARIABLES
    // Internals; generally not touched by application code
    VConvCombTest__Syms* __VlSymsp;  // Symbol table
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(VConvCombTest);  ///< Copying not allowed
  public:
    /// Construct the model; called by application code
    /// The special name  may be used to make a wrapper with a
    /// single model invisible with respect to DPI scope names.
    VConvCombTest(const char* name = "TOP");
    /// Destroy the model; called (often implicitly) by application code
    ~VConvCombTest();
    /// Trace signals in the model; called by application code
    void trace(VerilatedVcdC* tfp, int levels, int options = 0);
    
    // API METHODS
    /// Evaluate the model.  Application must call when inputs change.
    void eval();
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    
    // INTERNAL METHODS
  private:
    static void _eval_initial_loop(VConvCombTest__Syms* __restrict vlSymsp);
  public:
    void __Vconfigure(VConvCombTest__Syms* symsp, bool first);
  private:
    static QData _change_request(VConvCombTest__Syms* __restrict vlSymsp);
    static QData _change_request_1(VConvCombTest__Syms* __restrict vlSymsp);
    void _ctor_var_reset() VL_ATTR_COLD;
    void _ctor_var_reset_1() VL_ATTR_COLD;
  public:
    static void _eval(VConvCombTest__Syms* __restrict vlSymsp);
  private:
#ifdef VL_DEBUG
    void _eval_debug_assertions();
#endif  // VL_DEBUG
  public:
    static void _eval_initial(VConvCombTest__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _eval_settle(VConvCombTest__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__30(VConvCombTest__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _sequent__TOP__10(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__11(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__12(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__13(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__14(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__15(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__16(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__17(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__18(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__19(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__20(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__21(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__22(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__23(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__24(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__25(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__26(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__28(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__29(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__34(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__35(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__6(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__7(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__8(VConvCombTest__Syms* __restrict vlSymsp);
    static void _sequent__TOP__9(VConvCombTest__Syms* __restrict vlSymsp);
    static void _settle__TOP__31(VConvCombTest__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__32(VConvCombTest__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__33(VConvCombTest__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void traceChgThis(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__10(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__11(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__12(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__14(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__16(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__17(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__18(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__2(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__20(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__21(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__22(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__4(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__6(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__7(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__8(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceChgThis__9(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceFullThis(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceFullThis__1(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceFullThis__13(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceFullThis__15(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceFullThis__19(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceFullThis__3(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceFullThis__5(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceInitThis(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceInitThis__1(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceInitThis__2(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceInitThis__3(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceInitThis__4(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceInitThis__5(VConvCombTest__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) VL_ATTR_COLD;
    static void traceInit(VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceFull(VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceChg(VerilatedVcd* vcdp, void* userthis, uint32_t code);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
