// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary design header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef _VCombCDMABench_H_
#define _VCombCDMABench_H_

#include "verilated.h"
#include "VCombCDMABench__Inlines.h"
class VCombCDMABench__Syms;
class VerilatedVcd;

//----------

VL_MODULE(VCombCDMABench) {
  public:
    // CELLS
    // Public to allow access to /*verilator_public*/ items;
    // otherwise the application code can consider these internals.
    
    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(rf_clk,0,0);
    VL_IN8(clk,0,0);
    VL_IN8(reset,0,0);
    VL_IN8(axil4Ctrl_spread_aw_valid,0,0);
    VL_OUT8(axil4Ctrl_spread_aw_ready,0,0);
    VL_IN8(axil4Ctrl_spread_aw_payload_addr,7,0);
    VL_IN8(axil4Ctrl_spread_aw_payload_prot,2,0);
    VL_IN8(axil4Ctrl_spread_w_valid,0,0);
    VL_OUT8(axil4Ctrl_spread_w_ready,0,0);
    VL_IN8(axil4Ctrl_spread_w_payload_strb,3,0);
    VL_OUT8(axil4Ctrl_spread_b_valid,0,0);
    VL_IN8(axil4Ctrl_spread_b_ready,0,0);
    VL_OUT8(axil4Ctrl_spread_b_payload_resp,1,0);
    VL_IN8(axil4Ctrl_spread_ar_valid,0,0);
    VL_OUT8(axil4Ctrl_spread_ar_ready,0,0);
    VL_IN8(axil4Ctrl_spread_ar_payload_addr,7,0);
    VL_IN8(axil4Ctrl_spread_ar_payload_prot,2,0);
    VL_OUT8(axil4Ctrl_spread_r_valid,0,0);
    VL_IN8(axil4Ctrl_spread_r_ready,0,0);
    VL_OUT8(axil4Ctrl_spread_r_payload_resp,1,0);
    VL_IN8(axil4Ctrl_despread_aw_valid,0,0);
    VL_OUT8(axil4Ctrl_despread_aw_ready,0,0);
    VL_IN8(axil4Ctrl_despread_aw_payload_addr,7,0);
    VL_IN8(axil4Ctrl_despread_aw_payload_prot,2,0);
    VL_IN8(axil4Ctrl_despread_w_valid,0,0);
    VL_OUT8(axil4Ctrl_despread_w_ready,0,0);
    VL_IN8(axil4Ctrl_despread_w_payload_strb,3,0);
    VL_OUT8(axil4Ctrl_despread_b_valid,0,0);
    VL_IN8(axil4Ctrl_despread_b_ready,0,0);
    VL_OUT8(axil4Ctrl_despread_b_payload_resp,1,0);
    VL_IN8(axil4Ctrl_despread_ar_valid,0,0);
    VL_OUT8(axil4Ctrl_despread_ar_ready,0,0);
    VL_IN8(axil4Ctrl_despread_ar_payload_addr,7,0);
    VL_IN8(axil4Ctrl_despread_ar_payload_prot,2,0);
    VL_OUT8(axil4Ctrl_despread_r_valid,0,0);
    VL_IN8(axil4Ctrl_despread_r_ready,0,0);
    VL_OUT8(axil4Ctrl_despread_r_payload_resp,1,0);
    VL_IN8(base_iq_in_valid,0,0);
    VL_OUT8(base_iq_in_ready,0,0);
    VL_OUT8(base_sub_iqs_0_valid,0,0);
    VL_OUT8(base_sub_iqs_1_valid,0,0);
    VL_OUT8(base_sub_iqs_2_valid,0,0);
    VL_OUT8(base_sub_iqs_3_valid,0,0);
    VL_OUT8(base_sub_iqs_4_valid,0,0);
    VL_OUT8(base_sub_iqs_5_valid,0,0);
    VL_OUT8(base_sub_iqs_6_valid,0,0);
    VL_OUT8(base_sub_iqs_7_valid,0,0);
    VL_IN8(rf_resetn,0,0);
    VL_IN16(base_iq_in_payload_0_cha_i,15,0);
    VL_IN16(base_iq_in_payload_0_cha_q,15,0);
    VL_IN16(base_iq_in_payload_1_cha_i,15,0);
    VL_IN16(base_iq_in_payload_1_cha_q,15,0);
    VL_IN16(base_iq_in_payload_2_cha_i,15,0);
    VL_IN16(base_iq_in_payload_2_cha_q,15,0);
    VL_IN16(base_iq_in_payload_3_cha_i,15,0);
    VL_IN16(base_iq_in_payload_3_cha_q,15,0);
    VL_IN16(base_iq_in_payload_4_cha_i,15,0);
    VL_IN16(base_iq_in_payload_4_cha_q,15,0);
    VL_IN16(base_iq_in_payload_5_cha_i,15,0);
    VL_IN16(base_iq_in_payload_5_cha_q,15,0);
    VL_IN16(base_iq_in_payload_6_cha_i,15,0);
    VL_IN16(base_iq_in_payload_6_cha_q,15,0);
    VL_IN16(base_iq_in_payload_7_cha_i,15,0);
    VL_IN16(base_iq_in_payload_7_cha_q,15,0);
    VL_OUT16(base_sub_iqs_0_payload_cha_i,15,0);
    VL_OUT16(base_sub_iqs_0_payload_cha_q,15,0);
    VL_OUT16(base_sub_iqs_1_payload_cha_i,15,0);
    VL_OUT16(base_sub_iqs_1_payload_cha_q,15,0);
    VL_OUT16(base_sub_iqs_2_payload_cha_i,15,0);
    VL_OUT16(base_sub_iqs_2_payload_cha_q,15,0);
    VL_OUT16(base_sub_iqs_3_payload_cha_i,15,0);
    VL_OUT16(base_sub_iqs_3_payload_cha_q,15,0);
    VL_OUT16(base_sub_iqs_4_payload_cha_i,15,0);
    VL_OUT16(base_sub_iqs_4_payload_cha_q,15,0);
    VL_OUT16(base_sub_iqs_5_payload_cha_i,15,0);
    VL_OUT16(base_sub_iqs_5_payload_cha_q,15,0);
    VL_OUT16(base_sub_iqs_6_payload_cha_i,15,0);
    VL_OUT16(base_sub_iqs_6_payload_cha_q,15,0);
    VL_OUT16(base_sub_iqs_7_payload_cha_i,15,0);
    VL_OUT16(base_sub_iqs_7_payload_cha_q,15,0);
    VL_IN(axil4Ctrl_spread_w_payload_data,31,0);
    VL_OUT(axil4Ctrl_spread_r_payload_data,31,0);
    VL_IN(axil4Ctrl_despread_w_payload_data,31,0);
    VL_OUT(axil4Ctrl_despread_r_payload_data,31,0);
    
    // LOCAL SIGNALS
    // Internals; generally not touched by application code
    VL_SIG8(CombCDMABench__DOT__cdma_spread_axil4Ctrl_arready,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread_axil4Ctrl_arready,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread_base_iq_ready,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_code_sum_mod_iq_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__writeJoinEvent_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT___zz_writeJoinEvent_translated_ready,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT___zz_axil4Ctrl_bvalid_2,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT___zz_axil4Ctrl_bresp,1,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__axil4Ctrl_ar_rValid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__axil4Ctrl_ar_rData_addr,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__axil4Ctrl_ar_rData_prot,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__writeOccur,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__cdma_spread_bridge_clc_driver,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT___zz_dataIn,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT___zz_dataIn_1,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT___zz_dataIn_2,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT___zz_dataIn_3,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code_map_port0,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code_map_port1,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code_map_port2,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code_map_port3,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code_map_port4,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code_map_port5,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code_map_port6,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code_map_port7,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_1,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code_1,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code_2,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code_3,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code_4,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code_5,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code_6,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT___zz_code_7,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__when_CDMASpreading_l51,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__when_CDMASpreading_l65,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_16__DOT__mod_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_17__DOT__mod_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_18__DOT__mod_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_19__DOT__mod_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_20__DOT__mod_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_21__DOT__mod_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_22__DOT__mod_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_23__DOT__mod_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__clkCrossing_10__DOT__area_clkI_reg,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__clkCrossing_10__DOT__area_clkO_buf0,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__clkCrossing_10__DOT__area_clkO_buf1,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__clkCrossing_11__DOT__area_clkI_reg,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__clkCrossing_11__DOT__area_clkO_buf0,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__clkCrossing_11__DOT__area_clkO_buf1,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__clkCrossing_12__DOT__area_clkI_reg,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__clkCrossing_12__DOT__area_clkO_buf0,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__clkCrossing_12__DOT__area_clkO_buf1,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__clkCrossing_13__DOT__area_clkI_reg,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__clkCrossing_13__DOT__area_clkO_buf0,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__clkCrossing_13__DOT__area_clkO_buf1,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__clkCrossing_14__DOT__area_clkI_reg,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__clkCrossing_14__DOT__area_clkO_buf0,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__clkCrossing_14__DOT__area_clkO_buf1,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__writeJoinEvent_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT___zz_writeJoinEvent_translated_ready,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT___zz_axil4Ctrl_bvalid_2,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT___zz_axil4Ctrl_bresp,1,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__axil4Ctrl_ar_rValid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__axil4Ctrl_ar_rData_addr,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__axil4Ctrl_ar_rData_prot,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__writeOccur,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__cdma_spread_bridge_clc_driver,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT___zz_dataIn,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT___zz_dataIn_1,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT___zz_dataIn_2,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT___zz_dataIn_3,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT___zz_code_map_port0,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT___zz_code_map_port1,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT___zz_code_map_port2,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT___zz_code_map_port3,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT___zz_code_map_port4,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT___zz_code_map_port5,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT___zz_code_map_port6,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT___zz_code_map_port7,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT___zz_1,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT___zz_cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT___zz_base_iq_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT___zz_cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT___zz_base_iq_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT___zz_cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT___zz_base_iq_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT___zz_cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT___zz_base_iq_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT___zz_cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT___zz_base_iq_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT___zz_cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT___zz_base_iq_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT___zz_cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT___zz_base_iq_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT___zz_cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__cnt,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT___zz_base_iq_valid,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__clkCrossing_10__DOT__area_clkI_reg,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__clkCrossing_10__DOT__area_clkO_buf0,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__clkCrossing_10__DOT__area_clkO_buf1,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__clkCrossing_11__DOT__area_clkI_reg,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__clkCrossing_11__DOT__area_clkO_buf0,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__clkCrossing_11__DOT__area_clkO_buf1,0,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__clkCrossing_12__DOT__area_clkI_reg,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__clkCrossing_12__DOT__area_clkO_buf0,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__clkCrossing_12__DOT__area_clkO_buf1,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__clkCrossing_13__DOT__area_clkI_reg,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__clkCrossing_13__DOT__area_clkO_buf0,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__clkCrossing_13__DOT__area_clkO_buf1,7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__clkCrossing_14__DOT__area_clkI_reg,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__clkCrossing_14__DOT__area_clkO_buf0,2,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__clkCrossing_14__DOT__area_clkO_buf1,2,0);
    //char	__VpadToAlign255[1];
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_code_sum_mod_iq_payload_cha_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_code_sum_mod_iq_payload_cha_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_0_cha_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_0_cha_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_1_cha_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_1_cha_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_2_cha_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_2_cha_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_3_cha_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_3_cha_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_4_cha_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_4_cha_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_5_cha_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_5_cha_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_6_cha_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_6_cha_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_7_cha_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__flow_iq_data_vec_7_cha_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_16__DOT__mod_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_16__DOT__mod_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_17__DOT__mod_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_17__DOT__mod_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_18__DOT__mod_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_18__DOT__mod_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_19__DOT__mod_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_19__DOT__mod_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_20__DOT__mod_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_20__DOT__mod_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_21__DOT__mod_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_21__DOT__mod_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_22__DOT__mod_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_22__DOT__mod_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_23__DOT__mod_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__computeUnit_23__DOT__mod_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__base_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__base_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__data_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__data_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__base_i_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__base_q_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__base_i_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__base_q_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_16__DOT__shift_reg_7,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_17__DOT__shift_reg_7,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__base_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__base_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__data_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__data_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__base_i_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__base_q_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__base_i_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__base_q_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_16__DOT__shift_reg_7,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_17__DOT__shift_reg_7,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__base_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__base_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__data_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__data_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__base_i_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__base_q_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__base_i_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__base_q_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_16__DOT__shift_reg_7,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_17__DOT__shift_reg_7,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__base_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__base_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__data_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__data_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__base_i_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__base_q_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__base_i_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__base_q_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_16__DOT__shift_reg_7,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_17__DOT__shift_reg_7,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__base_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__base_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__data_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__data_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__base_i_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__base_q_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__base_i_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__base_q_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_16__DOT__shift_reg_7,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_17__DOT__shift_reg_7,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__base_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__base_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__data_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__data_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__base_i_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__base_q_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__base_i_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__base_q_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_16__DOT__shift_reg_7,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_17__DOT__shift_reg_7,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__base_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__base_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__data_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__data_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__base_i_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__base_q_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__base_i_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__base_q_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_16__DOT__shift_reg_7,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_17__DOT__shift_reg_7,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__base_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__base_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__data_i,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__data_q,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__base_i_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__base_q_next,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__base_i_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__base_q_next_regNext,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_16__DOT__shift_reg_7,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    VL_SIG16(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_17__DOT__shift_reg_7,15,0);
    VL_SIG(CombCDMABench__DOT__cdma_spread__DOT__readRsp_data,31,0);
    VL_SIG(CombCDMABench__DOT__cdma_despread__DOT__readRsp_data,31,0);
    //char	__VpadToAlign716[4];
    VL_SIG8(CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__code_map[8],7,0);
    VL_SIG8(CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__code_map[8],7,0);
    
    // LOCAL VARIABLES
    // Internals; generally not touched by application code
    VL_SIG8(__Vdlyvdim0__CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__code_map__v0,2,0);
    VL_SIG8(__Vdlyvval__CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__code_map__v0,7,0);
    VL_SIG8(__Vdlyvset__CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__code_map__v0,0,0);
    VL_SIG8(__Vdly__CombCDMABench__DOT__cdma_spread__DOT__rfClockArea_cdma_spread__DOT__cnt,2,0);
    VL_SIG8(__Vdlyvdim0__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__code_map__v0,2,0);
    VL_SIG8(__Vdlyvval__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__code_map__v0,7,0);
    VL_SIG8(__Vdlyvset__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__code_map__v0,0,0);
    VL_SIG8(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__cnt,2,0);
    VL_SIG8(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__cnt,2,0);
    VL_SIG8(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__cnt,2,0);
    VL_SIG8(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__cnt,2,0);
    VL_SIG8(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__cnt,2,0);
    VL_SIG8(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__cnt,2,0);
    VL_SIG8(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__cnt,2,0);
    VL_SIG8(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__cnt,2,0);
    VL_SIG8(__Vclklast__TOP__rf_clk,0,0);
    VL_SIG8(__Vclklast__TOP__clk,0,0);
    VL_SIG8(__Vclklast__TOP__reset,0,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_16__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_17__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_18__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_19__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_20__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_21__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_22__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_16__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_16__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_16__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_16__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_16__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_16__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_16__DOT__shift_reg_6,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_17__DOT__shift_reg_0,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_17__DOT__shift_reg_1,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_17__DOT__shift_reg_2,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_17__DOT__shift_reg_3,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_17__DOT__shift_reg_4,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_17__DOT__shift_reg_5,15,0);
    VL_SIG16(__Vdly__CombCDMABench__DOT__cdma_despread__DOT__rfClockArea_cdma_despread__DOT__computeUnit_23__DOT__shiftRegister_17__DOT__shift_reg_6,15,0);
    //char	__VpadToAlign982[2];
    VL_SIG(__Vm_traceActivity,31,0);
    
    // INTERNAL VARIABLES
    // Internals; generally not touched by application code
    VCombCDMABench__Syms*	__VlSymsp;		// Symbol table
    
    // PARAMETERS
    // Parameters marked /*verilator public*/ for use by application code
    
    // CONSTRUCTORS
  private:
    VCombCDMABench& operator= (const VCombCDMABench&);	///< Copying not allowed
    VCombCDMABench(const VCombCDMABench&);	///< Copying not allowed
  public:
    /// Construct the model; called by application code
    /// The special name  may be used to make a wrapper with a
    /// single model invisible WRT DPI scope names.
    VCombCDMABench(const char* name="TOP");
    /// Destroy the model; called (often implicitly) by application code
    ~VCombCDMABench();
    /// Trace signals in the model; called by application code
    void trace (VerilatedVcdC* tfp, int levels, int options=0);
    
    // USER METHODS
    
    // API METHODS
    /// Evaluate the model.  Application must call when inputs change.
    void eval();
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    
    // INTERNAL METHODS
  private:
    static void _eval_initial_loop(VCombCDMABench__Syms* __restrict vlSymsp);
  public:
    void __Vconfigure(VCombCDMABench__Syms* symsp, bool first);
  private:
    static QData	_change_request(VCombCDMABench__Syms* __restrict vlSymsp);
    static QData	_change_request_1(VCombCDMABench__Syms* __restrict vlSymsp);
  public:
    static void	_combo__TOP__18(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_combo__TOP__22(VCombCDMABench__Syms* __restrict vlSymsp);
  private:
    void	_configure_coverage(VCombCDMABench__Syms* __restrict vlSymsp, bool first);
    void	_ctor_var_reset();
    void	_ctor_var_reset_1();
  public:
    static void	_eval(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_eval_initial(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_eval_settle(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_initial__TOP__1(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__10(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__11(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__12(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__13(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__14(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__15(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__19(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__20(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__6(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__7(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__8(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__9(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_settle__TOP__16(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_settle__TOP__17(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	_settle__TOP__21(VCombCDMABench__Syms* __restrict vlSymsp);
    static void	traceChgThis(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__10(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__11(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__2(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__3(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__4(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__5(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__6(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__8(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__9(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceFullThis(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceFullThis__1(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceFullThis__12(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceFullThis__7(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceInitThis(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceInitThis__1(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceInitThis__2(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceInitThis__3(VCombCDMABench__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceInit (VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceFull (VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceChg  (VerilatedVcd* vcdp, void* userthis, uint32_t code);
} VL_ATTR_ALIGNED(128);

#endif  /*guard*/
