// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary design header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef _VOFDMEqualizer_H_
#define _VOFDMEqualizer_H_

#include "verilated.h"
class VOFDMEqualizer__Syms;
class VerilatedVcd;

//----------

VL_MODULE(VOFDMEqualizer) {
  public:
    // CELLS
    // Public to allow access to /*verilator_public*/ items;
    // otherwise the application code can consider these internals.
    
    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(clk,0,0);
    VL_IN8(reset,0,0);
    VL_IN8(raw_data_valid,0,0);
    VL_OUT8(raw_data_ready,0,0);
    VL_IN8(raw_data_payload_last,0,0);
    VL_OUT8(equalized_data_valid,0,0);
    VL_OUT8(equalized_data_payload_last,0,0);
    //char	__VpadToAlign7[1];
    VL_IN16(raw_data_payload_fragment_cha_i,15,0);
    VL_IN16(raw_data_payload_fragment_cha_q,15,0);
    VL_OUT16(equalized_data_payload_fragment_cha_i,15,0);
    VL_OUT16(equalized_data_payload_fragment_cha_q,15,0);
    
    // LOCAL SIGNALS
    // Internals; generally not touched by application code
    VL_SIG8(OFDMEqualizer__DOT___zz_cnt,5,0);
    VL_SIG8(OFDMEqualizer__DOT__cnt,5,0);
    VL_SIG8(OFDMEqualizer__DOT__train_en,0,0);
    VL_SIG8(OFDMEqualizer__DOT__when_OFDMEqualizer_l47,0,0);
    VL_SIG8(OFDMEqualizer__DOT__train_cnt,5,0);
    VL_SIG8(OFDMEqualizer__DOT__train_finished,0,0);
    VL_SIG8(OFDMEqualizer__DOT__when_OFDMEqualizer_l71,0,0);
    VL_SIG8(OFDMEqualizer__DOT__when_OFDMEqualizer_l69,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_ready_1,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_1,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_2,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_3,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_4,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_5,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_6,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_7,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_8,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_9,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_10,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_11,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_12,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_13,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_14,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_15,0,0);
    VL_SIG8(OFDMEqualizer__DOT__raw_data_payload_last_delay_16,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT___zz_x_sign,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT___zz_x_sign_1,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT___zz_x_sign_2,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT___zz_x_sign_3,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT___zz_x_sign_4,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT___zz_x_sign_5,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT___zz_x_sign_6,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT___zz_x_sign_7,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT___zz_x_sign_8,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT___zz_x_sign_9,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT___zz_x_sign_10,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT___zz_x_sign_11,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT___zz_x_sign_12,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT___zz_x_sign_13,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT___zz_x_sign_14,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__x_sign,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_1,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_2,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_3,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_4,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_5,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_6,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_7,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_8,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_9,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_10,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_11,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_12,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_13,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_14,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_15,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__train_en_delay_16,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid_1,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid_2,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid_3,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid_4,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid_5,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid_6,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid_7,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid_8,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid_9,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid_10,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid_11,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid_12,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid_13,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid_14,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_valid_15,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_46,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_47,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_48,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_49,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_50,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_51,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_52,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_53,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_54,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_55,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_56,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_57,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_58,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_59,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_60,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_75,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_78,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_81,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_84,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_87,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_90,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_93,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_96,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_99,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_102,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_105,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_108,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_111,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_114,0,0);
    VL_SIG8(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_117,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT___zz_x_sign,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT___zz_x_sign_1,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT___zz_x_sign_2,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT___zz_x_sign_3,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT___zz_x_sign_4,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT___zz_x_sign_5,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT___zz_x_sign_6,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT___zz_x_sign_7,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT___zz_x_sign_8,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT___zz_x_sign_9,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT___zz_x_sign_10,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT___zz_x_sign_11,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT___zz_x_sign_12,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT___zz_x_sign_13,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT___zz_x_sign_14,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__x_sign,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_1,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_2,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_3,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_4,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_5,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_6,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_7,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_8,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_9,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_10,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_11,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_12,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_13,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_14,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_15,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__train_en_delay_16,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid_1,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid_2,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid_3,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid_4,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid_5,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid_6,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid_7,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid_8,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid_9,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid_10,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid_11,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid_12,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid_13,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid_14,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_valid_15,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_46,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_47,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_48,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_49,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_50,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_51,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_52,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_53,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_54,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_55,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_56,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_57,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_58,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_59,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_60,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_75,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_78,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_81,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_84,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_87,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_90,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_93,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_96,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_99,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_102,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_105,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_108,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_111,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_114,0,0);
    VL_SIG8(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_117,0,0);
    //char	__VpadToAlign201[1];
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq_result_data_payload,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq_result_data_payload,15,0);
    VL_SIG16(OFDMEqualizer__DOT___zz_scale,15,0);
    VL_SIG16(OFDMEqualizer__DOT___zz_ref_data,15,0);
    VL_SIG16(OFDMEqualizer__DOT___zz_scale_1,15,0);
    VL_SIG16(OFDMEqualizer__DOT___zz_ref_data_1,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_0,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_1,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_2,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_3,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_4,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_5,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_6,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_7,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_8,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_9,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_10,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_11,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_12,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_13,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_14,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_15,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_16,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_17,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_18,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_19,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_20,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_21,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_22,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_23,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_24,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_25,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_26,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_27,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_28,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_29,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_30,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_31,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_32,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_33,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_34,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_35,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_36,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_37,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_38,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_39,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_40,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_41,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_42,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_43,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_44,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_45,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_46,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_47,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_48,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_49,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_50,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_51,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_52,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_53,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_54,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_55,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_56,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_57,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_58,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_59,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_60,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_61,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_62,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_ref_63,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_0,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_1,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_2,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_3,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_4,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_5,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_6,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_7,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_8,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_9,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_10,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_11,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_12,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_13,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_14,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_15,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_16,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_17,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_18,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_19,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_20,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_21,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_22,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_23,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_24,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_25,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_26,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_27,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_28,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_29,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_30,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_31,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_32,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_33,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_34,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_35,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_36,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_37,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_38,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_39,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_40,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_41,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_42,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_43,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_44,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_45,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_46,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_47,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_48,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_49,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_50,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_51,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_52,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_53,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_54,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_55,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_56,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_57,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_58,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_59,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_60,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_61,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_62,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_ref_63,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_0,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_1,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_2,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_3,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_4,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_5,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_6,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_7,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_8,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_9,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_10,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_11,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_12,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_13,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_14,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_15,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_16,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_17,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_18,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_19,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_20,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_21,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_22,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_23,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_24,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_25,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_26,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_27,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_28,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_29,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_30,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_31,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_32,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_33,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_34,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_35,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_36,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_37,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_38,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_39,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_40,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_41,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_42,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_43,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_44,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_45,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_46,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_47,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_48,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_49,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_50,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_51,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_52,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_53,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_54,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_55,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_56,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_57,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_58,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_59,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_60,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_61,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_62,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_i_scale_63,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_0,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_1,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_2,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_3,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_4,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_5,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_6,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_7,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_8,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_9,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_10,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_11,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_12,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_13,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_14,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_15,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_16,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_17,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_18,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_19,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_20,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_21,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_22,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_23,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_24,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_25,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_26,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_27,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_28,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_29,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_30,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_31,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_32,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_33,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_34,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_35,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_36,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_37,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_38,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_39,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_40,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_41,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_42,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_43,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_44,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_45,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_46,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_47,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_48,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_49,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_50,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_51,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_52,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_53,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_54,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_55,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_56,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_57,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_58,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_59,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_60,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_61,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_62,15,0);
    VL_SIG16(OFDMEqualizer__DOT__cha_q_scale_63,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_1,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_2,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_3,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_4,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_5,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_6,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_7,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_8,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_9,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_10,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_11,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_12,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_13,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_14,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_15,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_16,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_17,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_18,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_19,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_20,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_21,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_22,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_23,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_24,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_25,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_26,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_27,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_28,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_29,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_30,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_y,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_31,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_32,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_33,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_34,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_35,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_36,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_37,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_38,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_39,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_40,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_41,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_42,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_43,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_44,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_45,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_z,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_61,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_62,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_63,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_64,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_65,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_66,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_67,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_68,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_69,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_70,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_71,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_72,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_73,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_74,15,0);
    VL_SIG16(OFDMEqualizer__DOT__i_zf_eq__DOT__cal_core__DOT___zz_result_payload_z_1,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_1,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_2,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_3,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_4,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_5,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_6,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_7,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_8,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_9,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_10,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_11,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_12,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_13,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_14,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_15,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_16,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_17,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_18,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_19,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_20,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_21,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_22,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_23,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_24,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_25,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_26,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_27,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_28,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_29,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_30,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_y,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_31,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_32,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_33,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_34,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_35,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_36,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_37,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_38,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_39,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_40,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_41,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_42,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_43,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_44,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_45,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_z,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_61,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_62,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_63,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_64,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_65,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_66,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_67,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_68,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_69,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_70,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_71,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_72,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_73,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_x_74,15,0);
    VL_SIG16(OFDMEqualizer__DOT__q_zf_eq__DOT__cal_core__DOT___zz_result_payload_z_1,15,0);
    //char	__VpadToAlign978[2];
    
    // LOCAL VARIABLES
    // Internals; generally not touched by application code
    VL_SIG8(__Vdly__OFDMEqualizer__DOT__cnt,5,0);
    VL_SIG8(__Vclklast__TOP__clk,0,0);
    VL_SIG8(__Vclklast__TOP__reset,0,0);
    //char	__VpadToAlign987[1];
    VL_SIG(__Vm_traceActivity,31,0);
    
    // INTERNAL VARIABLES
    // Internals; generally not touched by application code
    //char	__VpadToAlign996[4];
    VOFDMEqualizer__Syms*	__VlSymsp;		// Symbol table
    
    // PARAMETERS
    // Parameters marked /*verilator public*/ for use by application code
    
    // CONSTRUCTORS
  private:
    VOFDMEqualizer& operator= (const VOFDMEqualizer&);	///< Copying not allowed
    VOFDMEqualizer(const VOFDMEqualizer&);	///< Copying not allowed
  public:
    /// Construct the model; called by application code
    /// The special name  may be used to make a wrapper with a
    /// single model invisible WRT DPI scope names.
    VOFDMEqualizer(const char* name="TOP");
    /// Destroy the model; called (often implicitly) by application code
    ~VOFDMEqualizer();
    /// Trace signals in the model; called by application code
    void trace (VerilatedVcdC* tfp, int levels, int options=0);
    
    // USER METHODS
    
    // API METHODS
    /// Evaluate the model.  Application must call when inputs change.
    void eval();
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    
    // INTERNAL METHODS
  private:
    static void _eval_initial_loop(VOFDMEqualizer__Syms* __restrict vlSymsp);
  public:
    void __Vconfigure(VOFDMEqualizer__Syms* symsp, bool first);
  private:
    static QData	_change_request(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static QData	_change_request_1(VOFDMEqualizer__Syms* __restrict vlSymsp);
    void	_configure_coverage(VOFDMEqualizer__Syms* __restrict vlSymsp, bool first);
    void	_ctor_var_reset();
    void	_ctor_var_reset_1();
  public:
    static void	_eval(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_eval_initial(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_eval_settle(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__10(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__11(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__12(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__13(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__14(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__15(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__16(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__17(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__18(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__19(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__21(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__22(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__25(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__9(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_settle__TOP__23(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	_settle__TOP__24(VOFDMEqualizer__Syms* __restrict vlSymsp);
    static void	traceChgThis(VOFDMEqualizer__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__2(VOFDMEqualizer__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__3(VOFDMEqualizer__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__4(VOFDMEqualizer__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__6(VOFDMEqualizer__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__7(VOFDMEqualizer__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__8(VOFDMEqualizer__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceFullThis(VOFDMEqualizer__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceFullThis__1(VOFDMEqualizer__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceFullThis__5(VOFDMEqualizer__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceInitThis(VOFDMEqualizer__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceInitThis__1(VOFDMEqualizer__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceInit (VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceFull (VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceChg  (VerilatedVcd* vcdp, void* userthis, uint32_t code);
} VL_ATTR_ALIGNED(128);

#endif  /*guard*/
