// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "VPreambleDetector__Syms.h"


//======================

void VPreambleDetector::trace(VerilatedVcdC* tfp, int, int) {
    tfp->spTrace()->addCallback(&VPreambleDetector::traceInit, &VPreambleDetector::traceFull, &VPreambleDetector::traceChg, this);
}
void VPreambleDetector::traceInit(VerilatedVcd* vcdp, void* userthis, uint32_t code) {
    // Callback from vcd->open()
    VPreambleDetector* t = (VPreambleDetector*)userthis;
    VPreambleDetector__Syms* __restrict vlSymsp = t->__VlSymsp;  // Setup global symbol table
    if (!Verilated::calcUnusedSigs()) {
        VL_FATAL_MT(__FILE__, __LINE__, __FILE__,
                        "Turning on wave traces requires Verilated::traceEverOn(true) call before time 0.");
    }
    vcdp->scopeEscape(' ');
    t->traceInitThis(vlSymsp, vcdp, code);
    vcdp->scopeEscape('.');
}
void VPreambleDetector::traceFull(VerilatedVcd* vcdp, void* userthis, uint32_t code) {
    // Callback from vcd->dump()
    VPreambleDetector* t = (VPreambleDetector*)userthis;
    VPreambleDetector__Syms* __restrict vlSymsp = t->__VlSymsp;  // Setup global symbol table
    t->traceFullThis(vlSymsp, vcdp, code);
}

//======================


void VPreambleDetector::traceInitThis(VPreambleDetector__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) {
    VPreambleDetector* __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    int c = code;
    if (0 && vcdp && c) {}  // Prevent unused
    vcdp->module(vlSymsp->name());  // Setup signal names
    // Body
    {
        vlTOPp->traceInitThis__1(vlSymsp, vcdp, code);
    }
}

void VPreambleDetector::traceFullThis(VPreambleDetector__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) {
    VPreambleDetector* __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    int c = code;
    if (0 && vcdp && c) {}  // Prevent unused
    // Body
    {
        vlTOPp->traceFullThis__1(vlSymsp, vcdp, code);
        vlTOPp->traceFullThis__4(vlSymsp, vcdp, code);
    }
    // Final
    vlTOPp->__Vm_traceActivity = 0U;
}

void VPreambleDetector::traceInitThis__1(VPreambleDetector__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) {
    VPreambleDetector* __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    int c = code;
    if (0 && vcdp && c) {}  // Prevent unused
    // Body
    {
        vcdp->declBus(c+2633,"gate_threshold", false,-1, 23,0);
        vcdp->declBit(c+2641,"pkg_detected", false,-1);
        vcdp->declBit(c+2649,"raw_data_valid", false,-1);
        vcdp->declBus(c+2657,"raw_data_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+2665,"raw_data_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+2673,"raw_data_out_valid", false,-1);
        vcdp->declBus(c+2681,"raw_data_out_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+2689,"raw_data_out_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+2697,"corr_result_valid", false,-1);
        vcdp->declBus(c+2705,"corr_result_payload_cha_i", false,-1, 23,0);
        vcdp->declBus(c+2713,"corr_result_payload_cha_q", false,-1, 23,0);
        vcdp->declBit(c+2721,"clk", false,-1);
        vcdp->declBit(c+2729,"reset", false,-1);
        vcdp->declBus(c+2633,"PreambleDetector gate_threshold", false,-1, 23,0);
        vcdp->declBit(c+2641,"PreambleDetector pkg_detected", false,-1);
        vcdp->declBit(c+2649,"PreambleDetector raw_data_valid", false,-1);
        vcdp->declBus(c+2657,"PreambleDetector raw_data_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+2665,"PreambleDetector raw_data_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+2673,"PreambleDetector raw_data_out_valid", false,-1);
        vcdp->declBus(c+2681,"PreambleDetector raw_data_out_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+2689,"PreambleDetector raw_data_out_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+2697,"PreambleDetector corr_result_valid", false,-1);
        vcdp->declBus(c+2705,"PreambleDetector corr_result_payload_cha_i", false,-1, 23,0);
        vcdp->declBus(c+2713,"PreambleDetector corr_result_payload_cha_q", false,-1, 23,0);
        vcdp->declBit(c+2721,"PreambleDetector clk", false,-1);
        vcdp->declBit(c+2729,"PreambleDetector reset", false,-1);
        vcdp->declBit(c+9,"PreambleDetector autoCorrelator_1_corr_result_valid", false,-1);
        vcdp->declBus(c+17,"PreambleDetector autoCorrelator_1_corr_result_payload_cha_i", false,-1, 23,0);
        vcdp->declBus(c+25,"PreambleDetector autoCorrelator_1_corr_result_payload_cha_q", false,-1, 23,0);
        vcdp->declBit(c+33,"PreambleDetector gate_pkg_det", false,-1);
        vcdp->declBus(c+41,"PreambleDetector prod_avg_mag", false,-1, 23,0);
        vcdp->declBit(c+2649,"PreambleDetector autoCorrelator_1 raw_data_valid", false,-1);
        vcdp->declBus(c+2657,"PreambleDetector autoCorrelator_1 raw_data_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+2665,"PreambleDetector autoCorrelator_1 raw_data_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+9,"PreambleDetector autoCorrelator_1 corr_result_valid", false,-1);
        vcdp->declBus(c+17,"PreambleDetector autoCorrelator_1 corr_result_payload_cha_i", false,-1, 23,0);
        vcdp->declBus(c+25,"PreambleDetector autoCorrelator_1 corr_result_payload_cha_q", false,-1, 23,0);
        vcdp->declBit(c+2721,"PreambleDetector autoCorrelator_1 clk", false,-1);
        vcdp->declBit(c+2729,"PreambleDetector autoCorrelator_1 reset", false,-1);
        vcdp->declBit(c+49,"PreambleDetector autoCorrelator_1 shiftRegister_3_output_valid", false,-1);
        vcdp->declBus(c+57,"PreambleDetector autoCorrelator_1 shiftRegister_3_output_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+65,"PreambleDetector autoCorrelator_1 shiftRegister_3_output_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+9,"PreambleDetector autoCorrelator_1 corr_core_corr_result_valid", false,-1);
        vcdp->declBus(c+17,"PreambleDetector autoCorrelator_1 corr_core_corr_result_payload_cha_i", false,-1, 23,0);
        vcdp->declBus(c+25,"PreambleDetector autoCorrelator_1 corr_core_corr_result_payload_cha_q", false,-1, 23,0);
        vcdp->declBit(c+2649,"PreambleDetector autoCorrelator_1 shiftRegister_3 input_valid", false,-1);
        vcdp->declBus(c+2657,"PreambleDetector autoCorrelator_1 shiftRegister_3 input_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+2665,"PreambleDetector autoCorrelator_1 shiftRegister_3 input_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+49,"PreambleDetector autoCorrelator_1 shiftRegister_3 output_valid", false,-1);
        vcdp->declBus(c+57,"PreambleDetector autoCorrelator_1 shiftRegister_3 output_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+65,"PreambleDetector autoCorrelator_1 shiftRegister_3 output_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+2649,"PreambleDetector autoCorrelator_1 shiftRegister_3 enable", false,-1);
        vcdp->declBit(c+2721,"PreambleDetector autoCorrelator_1 shiftRegister_3 clk", false,-1);
        vcdp->declBit(c+2729,"PreambleDetector autoCorrelator_1 shiftRegister_3 reset", false,-1);
        vcdp->declBit(c+73,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_0_valid", false,-1);
        vcdp->declBus(c+81,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_0_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+89,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_0_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+97,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_1_valid", false,-1);
        vcdp->declBus(c+105,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_1_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+113,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_1_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+121,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_2_valid", false,-1);
        vcdp->declBus(c+129,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_2_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+137,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_2_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+145,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_3_valid", false,-1);
        vcdp->declBus(c+153,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_3_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+161,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_3_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+169,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_4_valid", false,-1);
        vcdp->declBus(c+177,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_4_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+185,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_4_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+193,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_5_valid", false,-1);
        vcdp->declBus(c+201,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_5_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+209,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_5_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+217,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_6_valid", false,-1);
        vcdp->declBus(c+225,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_6_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+233,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_6_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+241,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_7_valid", false,-1);
        vcdp->declBus(c+249,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_7_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+257,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_7_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+265,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_8_valid", false,-1);
        vcdp->declBus(c+273,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_8_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+281,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_8_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+289,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_9_valid", false,-1);
        vcdp->declBus(c+297,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_9_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+305,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_9_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+313,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_10_valid", false,-1);
        vcdp->declBus(c+321,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_10_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+329,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_10_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+337,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_11_valid", false,-1);
        vcdp->declBus(c+345,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_11_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+353,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_11_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+361,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_12_valid", false,-1);
        vcdp->declBus(c+369,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_12_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+377,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_12_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+385,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_13_valid", false,-1);
        vcdp->declBus(c+393,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_13_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+401,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_13_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+409,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_14_valid", false,-1);
        vcdp->declBus(c+417,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_14_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+425,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_14_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+433,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_15_valid", false,-1);
        vcdp->declBus(c+441,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_15_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+449,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_15_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+457,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_16_valid", false,-1);
        vcdp->declBus(c+465,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_16_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+473,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_16_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+481,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_17_valid", false,-1);
        vcdp->declBus(c+489,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_17_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+497,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_17_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+505,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_18_valid", false,-1);
        vcdp->declBus(c+513,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_18_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+521,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_18_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+529,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_19_valid", false,-1);
        vcdp->declBus(c+537,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_19_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+545,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_19_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+553,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_20_valid", false,-1);
        vcdp->declBus(c+561,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_20_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+569,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_20_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+577,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_21_valid", false,-1);
        vcdp->declBus(c+585,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_21_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+593,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_21_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+601,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_22_valid", false,-1);
        vcdp->declBus(c+609,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_22_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+617,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_22_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+625,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_23_valid", false,-1);
        vcdp->declBus(c+633,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_23_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+641,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_23_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+649,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_24_valid", false,-1);
        vcdp->declBus(c+657,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_24_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+665,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_24_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+673,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_25_valid", false,-1);
        vcdp->declBus(c+681,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_25_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+689,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_25_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+697,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_26_valid", false,-1);
        vcdp->declBus(c+705,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_26_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+713,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_26_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+721,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_27_valid", false,-1);
        vcdp->declBus(c+729,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_27_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+737,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_27_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+745,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_28_valid", false,-1);
        vcdp->declBus(c+753,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_28_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+761,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_28_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+769,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_29_valid", false,-1);
        vcdp->declBus(c+777,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_29_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+785,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_29_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+793,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_30_valid", false,-1);
        vcdp->declBus(c+801,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_30_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+809,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_30_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+817,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_31_valid", false,-1);
        vcdp->declBus(c+825,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_31_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+833,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_31_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+841,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_32_valid", false,-1);
        vcdp->declBus(c+849,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_32_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+857,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_32_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+865,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_33_valid", false,-1);
        vcdp->declBus(c+873,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_33_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+881,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_33_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+889,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_34_valid", false,-1);
        vcdp->declBus(c+897,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_34_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+905,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_34_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+913,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_35_valid", false,-1);
        vcdp->declBus(c+921,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_35_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+929,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_35_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+937,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_36_valid", false,-1);
        vcdp->declBus(c+945,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_36_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+953,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_36_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+961,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_37_valid", false,-1);
        vcdp->declBus(c+969,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_37_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+977,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_37_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+985,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_38_valid", false,-1);
        vcdp->declBus(c+993,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_38_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1001,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_38_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1009,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_39_valid", false,-1);
        vcdp->declBus(c+1017,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_39_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1025,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_39_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1033,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_40_valid", false,-1);
        vcdp->declBus(c+1041,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_40_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1049,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_40_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1057,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_41_valid", false,-1);
        vcdp->declBus(c+1065,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_41_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1073,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_41_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1081,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_42_valid", false,-1);
        vcdp->declBus(c+1089,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_42_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1097,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_42_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1105,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_43_valid", false,-1);
        vcdp->declBus(c+1113,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_43_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1121,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_43_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1129,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_44_valid", false,-1);
        vcdp->declBus(c+1137,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_44_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1145,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_44_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1153,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_45_valid", false,-1);
        vcdp->declBus(c+1161,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_45_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1169,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_45_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1177,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_46_valid", false,-1);
        vcdp->declBus(c+1185,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_46_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1193,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_46_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1201,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_47_valid", false,-1);
        vcdp->declBus(c+1209,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_47_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1217,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_47_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1225,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_48_valid", false,-1);
        vcdp->declBus(c+1233,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_48_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1241,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_48_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1249,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_49_valid", false,-1);
        vcdp->declBus(c+1257,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_49_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1265,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_49_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1273,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_50_valid", false,-1);
        vcdp->declBus(c+1281,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_50_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1289,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_50_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1297,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_51_valid", false,-1);
        vcdp->declBus(c+1305,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_51_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1313,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_51_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1321,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_52_valid", false,-1);
        vcdp->declBus(c+1329,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_52_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1337,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_52_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1345,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_53_valid", false,-1);
        vcdp->declBus(c+1353,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_53_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1361,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_53_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1369,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_54_valid", false,-1);
        vcdp->declBus(c+1377,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_54_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1385,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_54_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1393,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_55_valid", false,-1);
        vcdp->declBus(c+1401,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_55_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1409,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_55_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1417,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_56_valid", false,-1);
        vcdp->declBus(c+1425,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_56_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1433,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_56_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1441,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_57_valid", false,-1);
        vcdp->declBus(c+1449,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_57_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1457,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_57_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1465,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_58_valid", false,-1);
        vcdp->declBus(c+1473,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_58_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1481,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_58_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1489,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_59_valid", false,-1);
        vcdp->declBus(c+1497,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_59_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1505,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_59_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1513,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_60_valid", false,-1);
        vcdp->declBus(c+1521,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_60_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1529,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_60_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1537,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_61_valid", false,-1);
        vcdp->declBus(c+1545,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_61_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1553,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_61_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+1561,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_62_valid", false,-1);
        vcdp->declBus(c+1569,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_62_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+1577,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_62_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+49,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_63_valid", false,-1);
        vcdp->declBus(c+57,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_63_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+65,"PreambleDetector autoCorrelator_1 shiftRegister_3 shift_reg_63_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+2649,"PreambleDetector autoCorrelator_1 corr_core raw_data_0_valid", false,-1);
        vcdp->declBus(c+2657,"PreambleDetector autoCorrelator_1 corr_core raw_data_0_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+2665,"PreambleDetector autoCorrelator_1 corr_core raw_data_0_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+49,"PreambleDetector autoCorrelator_1 corr_core raw_data_1_valid", false,-1);
        vcdp->declBus(c+57,"PreambleDetector autoCorrelator_1 corr_core raw_data_1_payload_cha_i", false,-1, 11,0);
        vcdp->declBus(c+65,"PreambleDetector autoCorrelator_1 corr_core raw_data_1_payload_cha_q", false,-1, 11,0);
        vcdp->declBit(c+9,"PreambleDetector autoCorrelator_1 corr_core corr_result_valid", false,-1);
        vcdp->declBus(c+17,"PreambleDetector autoCorrelator_1 corr_core corr_result_payload_cha_i", false,-1, 23,0);
        vcdp->declBus(c+25,"PreambleDetector autoCorrelator_1 corr_core corr_result_payload_cha_q", false,-1, 23,0);
        vcdp->declBit(c+2721,"PreambleDetector autoCorrelator_1 corr_core clk", false,-1);
        vcdp->declBit(c+2729,"PreambleDetector autoCorrelator_1 corr_core reset", false,-1);
        vcdp->declBus(c+1585,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3_output_1", false,-1, 23,0);
        vcdp->declBus(c+1593,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4_output_1", false,-1, 23,0);
        vcdp->declBus(c+17,"PreambleDetector autoCorrelator_1 corr_core corr_val_i", false,-1, 23,0);
        vcdp->declBus(c+25,"PreambleDetector autoCorrelator_1 corr_core corr_val_q", false,-1, 23,0);
        vcdp->declBus(c+1,"PreambleDetector autoCorrelator_1 corr_core k1", false,-1, 23,0);
        vcdp->declBus(c+2737,"PreambleDetector autoCorrelator_1 corr_core k2", false,-1, 23,0);
        vcdp->declBus(c+2745,"PreambleDetector autoCorrelator_1 corr_core k3", false,-1, 23,0);
        vcdp->declBus(c+1601,"PreambleDetector autoCorrelator_1 corr_core mul_i", false,-1, 23,0);
        vcdp->declBus(c+1609,"PreambleDetector autoCorrelator_1 corr_core mul_q", false,-1, 23,0);
        vcdp->declBit(c+1617,"PreambleDetector autoCorrelator_1 corr_core mul_data_valid", false,-1);
        vcdp->declBit(c+9,"PreambleDetector autoCorrelator_1 corr_core corr_result_valid_1", false,-1);
        vcdp->declBus(c+1601,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 input_1", false,-1, 23,0);
        vcdp->declBus(c+1585,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 output_1", false,-1, 23,0);
        vcdp->declBit(c+1617,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 enable", false,-1);
        vcdp->declBit(c+2721,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 clk", false,-1);
        vcdp->declBit(c+2729,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 reset", false,-1);
        vcdp->declBus(c+1625,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_0", false,-1, 23,0);
        vcdp->declBus(c+1633,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_1", false,-1, 23,0);
        vcdp->declBus(c+1641,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_2", false,-1, 23,0);
        vcdp->declBus(c+1649,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_3", false,-1, 23,0);
        vcdp->declBus(c+1657,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_4", false,-1, 23,0);
        vcdp->declBus(c+1665,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_5", false,-1, 23,0);
        vcdp->declBus(c+1673,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_6", false,-1, 23,0);
        vcdp->declBus(c+1681,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_7", false,-1, 23,0);
        vcdp->declBus(c+1689,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_8", false,-1, 23,0);
        vcdp->declBus(c+1697,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_9", false,-1, 23,0);
        vcdp->declBus(c+1705,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_10", false,-1, 23,0);
        vcdp->declBus(c+1713,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_11", false,-1, 23,0);
        vcdp->declBus(c+1721,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_12", false,-1, 23,0);
        vcdp->declBus(c+1729,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_13", false,-1, 23,0);
        vcdp->declBus(c+1737,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_14", false,-1, 23,0);
        vcdp->declBus(c+1745,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_15", false,-1, 23,0);
        vcdp->declBus(c+1753,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_16", false,-1, 23,0);
        vcdp->declBus(c+1761,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_17", false,-1, 23,0);
        vcdp->declBus(c+1769,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_18", false,-1, 23,0);
        vcdp->declBus(c+1777,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_19", false,-1, 23,0);
        vcdp->declBus(c+1785,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_20", false,-1, 23,0);
        vcdp->declBus(c+1793,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_21", false,-1, 23,0);
        vcdp->declBus(c+1801,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_22", false,-1, 23,0);
        vcdp->declBus(c+1809,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_23", false,-1, 23,0);
        vcdp->declBus(c+1817,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_24", false,-1, 23,0);
        vcdp->declBus(c+1825,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_25", false,-1, 23,0);
        vcdp->declBus(c+1833,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_26", false,-1, 23,0);
        vcdp->declBus(c+1841,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_27", false,-1, 23,0);
        vcdp->declBus(c+1849,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_28", false,-1, 23,0);
        vcdp->declBus(c+1857,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_29", false,-1, 23,0);
        vcdp->declBus(c+1865,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_30", false,-1, 23,0);
        vcdp->declBus(c+1873,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_31", false,-1, 23,0);
        vcdp->declBus(c+1881,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_32", false,-1, 23,0);
        vcdp->declBus(c+1889,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_33", false,-1, 23,0);
        vcdp->declBus(c+1897,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_34", false,-1, 23,0);
        vcdp->declBus(c+1905,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_35", false,-1, 23,0);
        vcdp->declBus(c+1913,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_36", false,-1, 23,0);
        vcdp->declBus(c+1921,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_37", false,-1, 23,0);
        vcdp->declBus(c+1929,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_38", false,-1, 23,0);
        vcdp->declBus(c+1937,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_39", false,-1, 23,0);
        vcdp->declBus(c+1945,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_40", false,-1, 23,0);
        vcdp->declBus(c+1953,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_41", false,-1, 23,0);
        vcdp->declBus(c+1961,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_42", false,-1, 23,0);
        vcdp->declBus(c+1969,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_43", false,-1, 23,0);
        vcdp->declBus(c+1977,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_44", false,-1, 23,0);
        vcdp->declBus(c+1985,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_45", false,-1, 23,0);
        vcdp->declBus(c+1993,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_46", false,-1, 23,0);
        vcdp->declBus(c+2001,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_47", false,-1, 23,0);
        vcdp->declBus(c+2009,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_48", false,-1, 23,0);
        vcdp->declBus(c+2017,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_49", false,-1, 23,0);
        vcdp->declBus(c+2025,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_50", false,-1, 23,0);
        vcdp->declBus(c+2033,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_51", false,-1, 23,0);
        vcdp->declBus(c+2041,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_52", false,-1, 23,0);
        vcdp->declBus(c+2049,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_53", false,-1, 23,0);
        vcdp->declBus(c+2057,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_54", false,-1, 23,0);
        vcdp->declBus(c+2065,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_55", false,-1, 23,0);
        vcdp->declBus(c+2073,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_56", false,-1, 23,0);
        vcdp->declBus(c+2081,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_57", false,-1, 23,0);
        vcdp->declBus(c+2089,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_58", false,-1, 23,0);
        vcdp->declBus(c+2097,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_59", false,-1, 23,0);
        vcdp->declBus(c+2105,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_60", false,-1, 23,0);
        vcdp->declBus(c+2113,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_61", false,-1, 23,0);
        vcdp->declBus(c+2121,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_62", false,-1, 23,0);
        vcdp->declBus(c+1585,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_3 shift_reg_63", false,-1, 23,0);
        vcdp->declBus(c+1609,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 input_1", false,-1, 23,0);
        vcdp->declBus(c+1593,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 output_1", false,-1, 23,0);
        vcdp->declBit(c+1617,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 enable", false,-1);
        vcdp->declBit(c+2721,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 clk", false,-1);
        vcdp->declBit(c+2729,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 reset", false,-1);
        vcdp->declBus(c+2129,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_0", false,-1, 23,0);
        vcdp->declBus(c+2137,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_1", false,-1, 23,0);
        vcdp->declBus(c+2145,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_2", false,-1, 23,0);
        vcdp->declBus(c+2153,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_3", false,-1, 23,0);
        vcdp->declBus(c+2161,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_4", false,-1, 23,0);
        vcdp->declBus(c+2169,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_5", false,-1, 23,0);
        vcdp->declBus(c+2177,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_6", false,-1, 23,0);
        vcdp->declBus(c+2185,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_7", false,-1, 23,0);
        vcdp->declBus(c+2193,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_8", false,-1, 23,0);
        vcdp->declBus(c+2201,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_9", false,-1, 23,0);
        vcdp->declBus(c+2209,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_10", false,-1, 23,0);
        vcdp->declBus(c+2217,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_11", false,-1, 23,0);
        vcdp->declBus(c+2225,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_12", false,-1, 23,0);
        vcdp->declBus(c+2233,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_13", false,-1, 23,0);
        vcdp->declBus(c+2241,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_14", false,-1, 23,0);
        vcdp->declBus(c+2249,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_15", false,-1, 23,0);
        vcdp->declBus(c+2257,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_16", false,-1, 23,0);
        vcdp->declBus(c+2265,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_17", false,-1, 23,0);
        vcdp->declBus(c+2273,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_18", false,-1, 23,0);
        vcdp->declBus(c+2281,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_19", false,-1, 23,0);
        vcdp->declBus(c+2289,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_20", false,-1, 23,0);
        vcdp->declBus(c+2297,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_21", false,-1, 23,0);
        vcdp->declBus(c+2305,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_22", false,-1, 23,0);
        vcdp->declBus(c+2313,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_23", false,-1, 23,0);
        vcdp->declBus(c+2321,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_24", false,-1, 23,0);
        vcdp->declBus(c+2329,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_25", false,-1, 23,0);
        vcdp->declBus(c+2337,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_26", false,-1, 23,0);
        vcdp->declBus(c+2345,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_27", false,-1, 23,0);
        vcdp->declBus(c+2353,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_28", false,-1, 23,0);
        vcdp->declBus(c+2361,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_29", false,-1, 23,0);
        vcdp->declBus(c+2369,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_30", false,-1, 23,0);
        vcdp->declBus(c+2377,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_31", false,-1, 23,0);
        vcdp->declBus(c+2385,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_32", false,-1, 23,0);
        vcdp->declBus(c+2393,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_33", false,-1, 23,0);
        vcdp->declBus(c+2401,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_34", false,-1, 23,0);
        vcdp->declBus(c+2409,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_35", false,-1, 23,0);
        vcdp->declBus(c+2417,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_36", false,-1, 23,0);
        vcdp->declBus(c+2425,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_37", false,-1, 23,0);
        vcdp->declBus(c+2433,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_38", false,-1, 23,0);
        vcdp->declBus(c+2441,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_39", false,-1, 23,0);
        vcdp->declBus(c+2449,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_40", false,-1, 23,0);
        vcdp->declBus(c+2457,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_41", false,-1, 23,0);
        vcdp->declBus(c+2465,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_42", false,-1, 23,0);
        vcdp->declBus(c+2473,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_43", false,-1, 23,0);
        vcdp->declBus(c+2481,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_44", false,-1, 23,0);
        vcdp->declBus(c+2489,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_45", false,-1, 23,0);
        vcdp->declBus(c+2497,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_46", false,-1, 23,0);
        vcdp->declBus(c+2505,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_47", false,-1, 23,0);
        vcdp->declBus(c+2513,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_48", false,-1, 23,0);
        vcdp->declBus(c+2521,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_49", false,-1, 23,0);
        vcdp->declBus(c+2529,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_50", false,-1, 23,0);
        vcdp->declBus(c+2537,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_51", false,-1, 23,0);
        vcdp->declBus(c+2545,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_52", false,-1, 23,0);
        vcdp->declBus(c+2553,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_53", false,-1, 23,0);
        vcdp->declBus(c+2561,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_54", false,-1, 23,0);
        vcdp->declBus(c+2569,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_55", false,-1, 23,0);
        vcdp->declBus(c+2577,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_56", false,-1, 23,0);
        vcdp->declBus(c+2585,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_57", false,-1, 23,0);
        vcdp->declBus(c+2593,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_58", false,-1, 23,0);
        vcdp->declBus(c+2601,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_59", false,-1, 23,0);
        vcdp->declBus(c+2609,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_60", false,-1, 23,0);
        vcdp->declBus(c+2617,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_61", false,-1, 23,0);
        vcdp->declBus(c+2625,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_62", false,-1, 23,0);
        vcdp->declBus(c+1593,"PreambleDetector autoCorrelator_1 corr_core shiftRegister_4 shift_reg_63", false,-1, 23,0);
    }
}

void VPreambleDetector::traceFullThis__1(VPreambleDetector__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) {
    VPreambleDetector* __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    int c = code;
    if (0 && vcdp && c) {}  // Prevent unused
    // Body
    {
        vcdp->fullBus(c+1,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__k1),24);
        vcdp->fullBit(c+9,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__corr_result_valid_1));
        vcdp->fullBus(c+17,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__corr_val_i),24);
        vcdp->fullBus(c+25,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__corr_val_q),24);
        vcdp->fullBit(c+33,(vlTOPp->PreambleDetector__DOT__gate_pkg_det));
        vcdp->fullBus(c+41,(vlTOPp->PreambleDetector__DOT__prod_avg_mag),24);
        vcdp->fullBit(c+49,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_63_valid));
        vcdp->fullBus(c+57,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_63_payload_cha_i),12);
        vcdp->fullBus(c+65,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_63_payload_cha_q),12);
        vcdp->fullBit(c+73,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_0_valid));
        vcdp->fullBus(c+81,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_0_payload_cha_i),12);
        vcdp->fullBus(c+89,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_0_payload_cha_q),12);
        vcdp->fullBit(c+97,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_1_valid));
        vcdp->fullBus(c+105,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_1_payload_cha_i),12);
        vcdp->fullBus(c+113,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_1_payload_cha_q),12);
        vcdp->fullBit(c+121,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_2_valid));
        vcdp->fullBus(c+129,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_2_payload_cha_i),12);
        vcdp->fullBus(c+137,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_2_payload_cha_q),12);
        vcdp->fullBit(c+145,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_3_valid));
        vcdp->fullBus(c+153,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_3_payload_cha_i),12);
        vcdp->fullBus(c+161,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_3_payload_cha_q),12);
        vcdp->fullBit(c+169,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_4_valid));
        vcdp->fullBus(c+177,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_4_payload_cha_i),12);
        vcdp->fullBus(c+185,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_4_payload_cha_q),12);
        vcdp->fullBit(c+193,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_5_valid));
        vcdp->fullBus(c+201,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_5_payload_cha_i),12);
        vcdp->fullBus(c+209,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_5_payload_cha_q),12);
        vcdp->fullBit(c+217,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_6_valid));
        vcdp->fullBus(c+225,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_6_payload_cha_i),12);
        vcdp->fullBus(c+233,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_6_payload_cha_q),12);
        vcdp->fullBit(c+241,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_7_valid));
        vcdp->fullBus(c+249,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_7_payload_cha_i),12);
        vcdp->fullBus(c+257,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_7_payload_cha_q),12);
        vcdp->fullBit(c+265,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_8_valid));
        vcdp->fullBus(c+273,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_8_payload_cha_i),12);
        vcdp->fullBus(c+281,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_8_payload_cha_q),12);
        vcdp->fullBit(c+289,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_9_valid));
        vcdp->fullBus(c+297,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_9_payload_cha_i),12);
        vcdp->fullBus(c+305,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_9_payload_cha_q),12);
        vcdp->fullBit(c+313,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_10_valid));
        vcdp->fullBus(c+321,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_10_payload_cha_i),12);
        vcdp->fullBus(c+329,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_10_payload_cha_q),12);
        vcdp->fullBit(c+337,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_11_valid));
        vcdp->fullBus(c+345,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_11_payload_cha_i),12);
        vcdp->fullBus(c+353,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_11_payload_cha_q),12);
        vcdp->fullBit(c+361,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_12_valid));
        vcdp->fullBus(c+369,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_12_payload_cha_i),12);
        vcdp->fullBus(c+377,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_12_payload_cha_q),12);
        vcdp->fullBit(c+385,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_13_valid));
        vcdp->fullBus(c+393,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_13_payload_cha_i),12);
        vcdp->fullBus(c+401,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_13_payload_cha_q),12);
        vcdp->fullBit(c+409,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_14_valid));
        vcdp->fullBus(c+417,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_14_payload_cha_i),12);
        vcdp->fullBus(c+425,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_14_payload_cha_q),12);
        vcdp->fullBit(c+433,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_15_valid));
        vcdp->fullBus(c+441,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_15_payload_cha_i),12);
        vcdp->fullBus(c+449,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_15_payload_cha_q),12);
        vcdp->fullBit(c+457,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_16_valid));
        vcdp->fullBus(c+465,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_16_payload_cha_i),12);
        vcdp->fullBus(c+473,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_16_payload_cha_q),12);
        vcdp->fullBit(c+481,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_17_valid));
        vcdp->fullBus(c+489,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_17_payload_cha_i),12);
        vcdp->fullBus(c+497,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_17_payload_cha_q),12);
        vcdp->fullBit(c+505,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_18_valid));
        vcdp->fullBus(c+513,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_18_payload_cha_i),12);
        vcdp->fullBus(c+521,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_18_payload_cha_q),12);
        vcdp->fullBit(c+529,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_19_valid));
        vcdp->fullBus(c+537,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_19_payload_cha_i),12);
        vcdp->fullBus(c+545,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_19_payload_cha_q),12);
        vcdp->fullBit(c+553,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_20_valid));
        vcdp->fullBus(c+561,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_20_payload_cha_i),12);
        vcdp->fullBus(c+569,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_20_payload_cha_q),12);
        vcdp->fullBit(c+577,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_21_valid));
        vcdp->fullBus(c+585,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_21_payload_cha_i),12);
        vcdp->fullBus(c+593,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_21_payload_cha_q),12);
        vcdp->fullBit(c+601,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_22_valid));
        vcdp->fullBus(c+609,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_22_payload_cha_i),12);
        vcdp->fullBus(c+617,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_22_payload_cha_q),12);
        vcdp->fullBit(c+625,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_23_valid));
        vcdp->fullBus(c+633,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_23_payload_cha_i),12);
        vcdp->fullBus(c+641,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_23_payload_cha_q),12);
        vcdp->fullBit(c+649,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_24_valid));
        vcdp->fullBus(c+657,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_24_payload_cha_i),12);
        vcdp->fullBus(c+665,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_24_payload_cha_q),12);
        vcdp->fullBit(c+673,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_25_valid));
        vcdp->fullBus(c+681,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_25_payload_cha_i),12);
        vcdp->fullBus(c+689,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_25_payload_cha_q),12);
        vcdp->fullBit(c+697,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_26_valid));
        vcdp->fullBus(c+705,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_26_payload_cha_i),12);
        vcdp->fullBus(c+713,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_26_payload_cha_q),12);
        vcdp->fullBit(c+721,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_27_valid));
        vcdp->fullBus(c+729,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_27_payload_cha_i),12);
        vcdp->fullBus(c+737,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_27_payload_cha_q),12);
        vcdp->fullBit(c+745,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_28_valid));
        vcdp->fullBus(c+753,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_28_payload_cha_i),12);
        vcdp->fullBus(c+761,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_28_payload_cha_q),12);
        vcdp->fullBit(c+769,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_29_valid));
        vcdp->fullBus(c+777,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_29_payload_cha_i),12);
        vcdp->fullBus(c+785,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_29_payload_cha_q),12);
        vcdp->fullBit(c+793,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_30_valid));
        vcdp->fullBus(c+801,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_30_payload_cha_i),12);
        vcdp->fullBus(c+809,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_30_payload_cha_q),12);
        vcdp->fullBit(c+817,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_31_valid));
        vcdp->fullBus(c+825,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_31_payload_cha_i),12);
        vcdp->fullBus(c+833,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_31_payload_cha_q),12);
        vcdp->fullBit(c+841,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_32_valid));
        vcdp->fullBus(c+849,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_32_payload_cha_i),12);
        vcdp->fullBus(c+857,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_32_payload_cha_q),12);
        vcdp->fullBit(c+865,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_33_valid));
        vcdp->fullBus(c+873,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_33_payload_cha_i),12);
        vcdp->fullBus(c+881,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_33_payload_cha_q),12);
        vcdp->fullBit(c+889,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_34_valid));
        vcdp->fullBus(c+897,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_34_payload_cha_i),12);
        vcdp->fullBus(c+905,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_34_payload_cha_q),12);
        vcdp->fullBit(c+913,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_35_valid));
        vcdp->fullBus(c+921,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_35_payload_cha_i),12);
        vcdp->fullBus(c+929,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_35_payload_cha_q),12);
        vcdp->fullBit(c+937,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_36_valid));
        vcdp->fullBus(c+945,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_36_payload_cha_i),12);
        vcdp->fullBus(c+953,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_36_payload_cha_q),12);
        vcdp->fullBit(c+961,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_37_valid));
        vcdp->fullBus(c+969,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_37_payload_cha_i),12);
        vcdp->fullBus(c+977,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_37_payload_cha_q),12);
        vcdp->fullBit(c+985,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_38_valid));
        vcdp->fullBus(c+993,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_38_payload_cha_i),12);
        vcdp->fullBus(c+1001,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_38_payload_cha_q),12);
        vcdp->fullBit(c+1009,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_39_valid));
        vcdp->fullBus(c+1017,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_39_payload_cha_i),12);
        vcdp->fullBus(c+1025,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_39_payload_cha_q),12);
        vcdp->fullBit(c+1033,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_40_valid));
        vcdp->fullBus(c+1041,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_40_payload_cha_i),12);
        vcdp->fullBus(c+1049,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_40_payload_cha_q),12);
        vcdp->fullBit(c+1057,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_41_valid));
        vcdp->fullBus(c+1065,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_41_payload_cha_i),12);
        vcdp->fullBus(c+1073,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_41_payload_cha_q),12);
        vcdp->fullBit(c+1081,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_42_valid));
        vcdp->fullBus(c+1089,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_42_payload_cha_i),12);
        vcdp->fullBus(c+1097,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_42_payload_cha_q),12);
        vcdp->fullBit(c+1105,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_43_valid));
        vcdp->fullBus(c+1113,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_43_payload_cha_i),12);
        vcdp->fullBus(c+1121,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_43_payload_cha_q),12);
        vcdp->fullBit(c+1129,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_44_valid));
        vcdp->fullBus(c+1137,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_44_payload_cha_i),12);
        vcdp->fullBus(c+1145,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_44_payload_cha_q),12);
        vcdp->fullBit(c+1153,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_45_valid));
        vcdp->fullBus(c+1161,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_45_payload_cha_i),12);
        vcdp->fullBus(c+1169,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_45_payload_cha_q),12);
        vcdp->fullBit(c+1177,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_46_valid));
        vcdp->fullBus(c+1185,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_46_payload_cha_i),12);
        vcdp->fullBus(c+1193,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_46_payload_cha_q),12);
        vcdp->fullBit(c+1201,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_47_valid));
        vcdp->fullBus(c+1209,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_47_payload_cha_i),12);
        vcdp->fullBus(c+1217,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_47_payload_cha_q),12);
        vcdp->fullBit(c+1225,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_48_valid));
        vcdp->fullBus(c+1233,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_48_payload_cha_i),12);
        vcdp->fullBus(c+1241,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_48_payload_cha_q),12);
        vcdp->fullBit(c+1249,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_49_valid));
        vcdp->fullBus(c+1257,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_49_payload_cha_i),12);
        vcdp->fullBus(c+1265,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_49_payload_cha_q),12);
        vcdp->fullBit(c+1273,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_50_valid));
        vcdp->fullBus(c+1281,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_50_payload_cha_i),12);
        vcdp->fullBus(c+1289,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_50_payload_cha_q),12);
        vcdp->fullBit(c+1297,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_51_valid));
        vcdp->fullBus(c+1305,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_51_payload_cha_i),12);
        vcdp->fullBus(c+1313,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_51_payload_cha_q),12);
        vcdp->fullBit(c+1321,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_52_valid));
        vcdp->fullBus(c+1329,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_52_payload_cha_i),12);
        vcdp->fullBus(c+1337,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_52_payload_cha_q),12);
        vcdp->fullBit(c+1345,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_53_valid));
        vcdp->fullBus(c+1353,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_53_payload_cha_i),12);
        vcdp->fullBus(c+1361,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_53_payload_cha_q),12);
        vcdp->fullBit(c+1369,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_54_valid));
        vcdp->fullBus(c+1377,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_54_payload_cha_i),12);
        vcdp->fullBus(c+1385,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_54_payload_cha_q),12);
        vcdp->fullBit(c+1393,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_55_valid));
        vcdp->fullBus(c+1401,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_55_payload_cha_i),12);
        vcdp->fullBus(c+1409,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_55_payload_cha_q),12);
        vcdp->fullBit(c+1417,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_56_valid));
        vcdp->fullBus(c+1425,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_56_payload_cha_i),12);
        vcdp->fullBus(c+1433,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_56_payload_cha_q),12);
        vcdp->fullBit(c+1441,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_57_valid));
        vcdp->fullBus(c+1449,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_57_payload_cha_i),12);
        vcdp->fullBus(c+1457,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_57_payload_cha_q),12);
        vcdp->fullBit(c+1465,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_58_valid));
        vcdp->fullBus(c+1473,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_58_payload_cha_i),12);
        vcdp->fullBus(c+1481,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_58_payload_cha_q),12);
        vcdp->fullBit(c+1489,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_59_valid));
        vcdp->fullBus(c+1497,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_59_payload_cha_i),12);
        vcdp->fullBus(c+1505,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_59_payload_cha_q),12);
        vcdp->fullBit(c+1513,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_60_valid));
        vcdp->fullBus(c+1521,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_60_payload_cha_i),12);
        vcdp->fullBus(c+1529,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_60_payload_cha_q),12);
        vcdp->fullBit(c+1537,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_61_valid));
        vcdp->fullBus(c+1545,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_61_payload_cha_i),12);
        vcdp->fullBus(c+1553,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_61_payload_cha_q),12);
        vcdp->fullBit(c+1561,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_62_valid));
        vcdp->fullBus(c+1569,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_62_payload_cha_i),12);
        vcdp->fullBus(c+1577,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_62_payload_cha_q),12);
        vcdp->fullBus(c+1585,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_63),24);
        vcdp->fullBus(c+1593,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_63),24);
        vcdp->fullBus(c+1601,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__mul_i),24);
        vcdp->fullBus(c+1609,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__mul_q),24);
        vcdp->fullBit(c+1617,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__mul_data_valid));
        vcdp->fullBus(c+1625,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_0),24);
        vcdp->fullBus(c+1633,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_1),24);
        vcdp->fullBus(c+1641,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_2),24);
        vcdp->fullBus(c+1649,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_3),24);
        vcdp->fullBus(c+1657,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_4),24);
        vcdp->fullBus(c+1665,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_5),24);
        vcdp->fullBus(c+1673,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_6),24);
        vcdp->fullBus(c+1681,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_7),24);
        vcdp->fullBus(c+1689,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_8),24);
        vcdp->fullBus(c+1697,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_9),24);
        vcdp->fullBus(c+1705,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_10),24);
        vcdp->fullBus(c+1713,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_11),24);
        vcdp->fullBus(c+1721,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_12),24);
        vcdp->fullBus(c+1729,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_13),24);
        vcdp->fullBus(c+1737,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_14),24);
        vcdp->fullBus(c+1745,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_15),24);
        vcdp->fullBus(c+1753,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_16),24);
        vcdp->fullBus(c+1761,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_17),24);
        vcdp->fullBus(c+1769,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_18),24);
        vcdp->fullBus(c+1777,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_19),24);
        vcdp->fullBus(c+1785,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_20),24);
        vcdp->fullBus(c+1793,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_21),24);
        vcdp->fullBus(c+1801,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_22),24);
        vcdp->fullBus(c+1809,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_23),24);
        vcdp->fullBus(c+1817,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_24),24);
        vcdp->fullBus(c+1825,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_25),24);
        vcdp->fullBus(c+1833,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_26),24);
        vcdp->fullBus(c+1841,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_27),24);
        vcdp->fullBus(c+1849,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_28),24);
        vcdp->fullBus(c+1857,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_29),24);
        vcdp->fullBus(c+1865,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_30),24);
        vcdp->fullBus(c+1873,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_31),24);
        vcdp->fullBus(c+1881,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_32),24);
        vcdp->fullBus(c+1889,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_33),24);
        vcdp->fullBus(c+1897,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_34),24);
        vcdp->fullBus(c+1905,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_35),24);
        vcdp->fullBus(c+1913,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_36),24);
        vcdp->fullBus(c+1921,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_37),24);
        vcdp->fullBus(c+1929,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_38),24);
        vcdp->fullBus(c+1937,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_39),24);
        vcdp->fullBus(c+1945,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_40),24);
        vcdp->fullBus(c+1953,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_41),24);
        vcdp->fullBus(c+1961,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_42),24);
        vcdp->fullBus(c+1969,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_43),24);
        vcdp->fullBus(c+1977,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_44),24);
        vcdp->fullBus(c+1985,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_45),24);
        vcdp->fullBus(c+1993,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_46),24);
        vcdp->fullBus(c+2001,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_47),24);
    }
}

void VPreambleDetector::traceFullThis__4(VPreambleDetector__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code) {
    VPreambleDetector* __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    int c = code;
    if (0 && vcdp && c) {}  // Prevent unused
    // Body
    {
        vcdp->fullBus(c+2009,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_48),24);
        vcdp->fullBus(c+2017,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_49),24);
        vcdp->fullBus(c+2025,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_50),24);
        vcdp->fullBus(c+2033,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_51),24);
        vcdp->fullBus(c+2041,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_52),24);
        vcdp->fullBus(c+2049,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_53),24);
        vcdp->fullBus(c+2057,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_54),24);
        vcdp->fullBus(c+2065,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_55),24);
        vcdp->fullBus(c+2073,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_56),24);
        vcdp->fullBus(c+2081,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_57),24);
        vcdp->fullBus(c+2089,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_58),24);
        vcdp->fullBus(c+2097,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_59),24);
        vcdp->fullBus(c+2105,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_60),24);
        vcdp->fullBus(c+2113,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_61),24);
        vcdp->fullBus(c+2121,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_3__DOT__shift_reg_62),24);
        vcdp->fullBus(c+2129,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_0),24);
        vcdp->fullBus(c+2137,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_1),24);
        vcdp->fullBus(c+2145,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_2),24);
        vcdp->fullBus(c+2153,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_3),24);
        vcdp->fullBus(c+2161,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_4),24);
        vcdp->fullBus(c+2169,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_5),24);
        vcdp->fullBus(c+2177,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_6),24);
        vcdp->fullBus(c+2185,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_7),24);
        vcdp->fullBus(c+2193,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_8),24);
        vcdp->fullBus(c+2201,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_9),24);
        vcdp->fullBus(c+2209,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_10),24);
        vcdp->fullBus(c+2217,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_11),24);
        vcdp->fullBus(c+2225,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_12),24);
        vcdp->fullBus(c+2233,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_13),24);
        vcdp->fullBus(c+2241,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_14),24);
        vcdp->fullBus(c+2249,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_15),24);
        vcdp->fullBus(c+2257,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_16),24);
        vcdp->fullBus(c+2265,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_17),24);
        vcdp->fullBus(c+2273,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_18),24);
        vcdp->fullBus(c+2281,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_19),24);
        vcdp->fullBus(c+2289,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_20),24);
        vcdp->fullBus(c+2297,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_21),24);
        vcdp->fullBus(c+2305,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_22),24);
        vcdp->fullBus(c+2313,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_23),24);
        vcdp->fullBus(c+2321,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_24),24);
        vcdp->fullBus(c+2329,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_25),24);
        vcdp->fullBus(c+2337,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_26),24);
        vcdp->fullBus(c+2345,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_27),24);
        vcdp->fullBus(c+2353,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_28),24);
        vcdp->fullBus(c+2361,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_29),24);
        vcdp->fullBus(c+2369,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_30),24);
        vcdp->fullBus(c+2377,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_31),24);
        vcdp->fullBus(c+2385,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_32),24);
        vcdp->fullBus(c+2393,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_33),24);
        vcdp->fullBus(c+2401,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_34),24);
        vcdp->fullBus(c+2409,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_35),24);
        vcdp->fullBus(c+2417,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_36),24);
        vcdp->fullBus(c+2425,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_37),24);
        vcdp->fullBus(c+2433,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_38),24);
        vcdp->fullBus(c+2441,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_39),24);
        vcdp->fullBus(c+2449,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_40),24);
        vcdp->fullBus(c+2457,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_41),24);
        vcdp->fullBus(c+2465,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_42),24);
        vcdp->fullBus(c+2473,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_43),24);
        vcdp->fullBus(c+2481,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_44),24);
        vcdp->fullBus(c+2489,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_45),24);
        vcdp->fullBus(c+2497,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_46),24);
        vcdp->fullBus(c+2505,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_47),24);
        vcdp->fullBus(c+2513,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_48),24);
        vcdp->fullBus(c+2521,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_49),24);
        vcdp->fullBus(c+2529,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_50),24);
        vcdp->fullBus(c+2537,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_51),24);
        vcdp->fullBus(c+2545,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_52),24);
        vcdp->fullBus(c+2553,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_53),24);
        vcdp->fullBus(c+2561,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_54),24);
        vcdp->fullBus(c+2569,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_55),24);
        vcdp->fullBus(c+2577,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_56),24);
        vcdp->fullBus(c+2585,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_57),24);
        vcdp->fullBus(c+2593,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_58),24);
        vcdp->fullBus(c+2601,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_59),24);
        vcdp->fullBus(c+2609,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_60),24);
        vcdp->fullBus(c+2617,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_61),24);
        vcdp->fullBus(c+2625,(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__corr_core__DOT__shiftRegister_4__DOT__shift_reg_62),24);
        vcdp->fullBus(c+2633,(vlTOPp->gate_threshold),24);
        vcdp->fullBit(c+2641,(vlTOPp->pkg_detected));
        vcdp->fullBit(c+2649,(vlTOPp->raw_data_valid));
        vcdp->fullBus(c+2657,(vlTOPp->raw_data_payload_cha_i),12);
        vcdp->fullBus(c+2665,(vlTOPp->raw_data_payload_cha_q),12);
        vcdp->fullBit(c+2673,(vlTOPp->raw_data_out_valid));
        vcdp->fullBus(c+2681,(vlTOPp->raw_data_out_payload_cha_i),12);
        vcdp->fullBus(c+2689,(vlTOPp->raw_data_out_payload_cha_q),12);
        vcdp->fullBit(c+2697,(vlTOPp->corr_result_valid));
        vcdp->fullBus(c+2705,(vlTOPp->corr_result_payload_cha_i),24);
        vcdp->fullBus(c+2713,(vlTOPp->corr_result_payload_cha_q),24);
        vcdp->fullBit(c+2721,(vlTOPp->clk));
        vcdp->fullBit(c+2729,(vlTOPp->reset));
        vcdp->fullBus(c+2737,((0xffffffU & VL_MULS_III(24,24,24, 
                                                       (0xffffffU 
                                                        & VL_EXTENDS_II(24,12, (IData)(vlTOPp->raw_data_payload_cha_i))), 
                                                       (0xffffffU 
                                                        & VL_EXTENDS_II(24,12, 
                                                                        (0xfffU 
                                                                         & ((IData)(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_63_payload_cha_q) 
                                                                            + (IData)(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_63_payload_cha_i)))))))),24);
        vcdp->fullBus(c+2745,((0xffffffU & VL_MULS_III(24,24,24, 
                                                       (0xffffffU 
                                                        & VL_EXTENDS_II(24,12, (IData)(vlTOPp->raw_data_payload_cha_q))), 
                                                       (0xffffffU 
                                                        & VL_EXTENDS_II(24,12, 
                                                                        (0xfffU 
                                                                         & ((IData)(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_63_payload_cha_i) 
                                                                            - (IData)(vlTOPp->PreambleDetector__DOT__autoCorrelator_1__DOT__shiftRegister_3__DOT__shift_reg_63_payload_cha_q)))))))),24);
    }
}
